# Generated by Django 3.2.2 on 2022-01-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField(verbose_name='Описание книги')),
                ('Year', models.PositiveIntegerField(verbose_name='Год написания')),
                ('PopularityRating', models.PositiveIntegerField(verbose_name='Место в рейтинге')),
                ('BookTitle', models.TextField(verbose_name='Название книги')),
                ('Author', models.TextField(verbose_name='Автор')),
                ('Genre', models.TextField(verbose_name='Жанр')),
                ('FirstPoblicationYear', models.PositiveIntegerField(verbose_name='Год первой публикации')),
                ('Publisher', models.TextField(verbose_name='Издательство, опубликовавшее книгу')),
                ('OriginalLanguage', models.TextField(verbose_name='Оригинальный язык')),
                ('Country', models.TextField(verbose_name='Страна в которой написана книга')),
            ],
        ),
    ]
